const weather_association = () => {
  const dat = {
    "200": "Thunderstorm with light rain",
    "201": "Thunderstorm with rain",
    "202": "Thunderstorm wtih heavy rain",
    "230": "Thunderstorm with light drizzle",
    "231": "Thunderstorm with drizzle",
    "232": "Thunderstorm with heavy drizzle",
    "233": "Thunderstorm with Hail",
    "300": "Light Drizzle",
    "301": "Drizzle",
    "302": "Heavy Drizzle",
    "500": "Light Rain",
    "501": "Moderate Rain",
    "502": "Heavy Rain",
    "511": "Freezing Rain",
    "520": "Light shower rain",
    "521": "Shower rain",
    "522": "Heacy shower rain",
    "600": "Light snow",
    "601": "Snow",
    "602": "Heavy Snow",
    "610": "Mix snow/rain",
    "611": "Sleet",
    "612": "Heavy sleet",
    "621": "Snow shower",
    "622": "Heavy Snow Shower",
    "623": "Flurries",
    "700": "Mist",
    "711": "Smoke",
    "721": "Haze",
    "731": "Sand/dust",
    "741": "Fog",
    "751": "Freezing Fog",
    "800": "Clear sky",
    "801": "Few clouds",
    "802": "Scattered Clouds",
    "803": "Broken Clouds",
    "804": "Overcast clouds",
    "900": "Unknown Percipitation",
  };
  return dat;
};

export default weather_association;
